// STORE KEYS

export const DRAWS_TO_SKIP = 'DRAWS_TO_SKIP';
export const PARTICLE_GROWTH_RATE = 'PARTICLE_GROWTH_RATE';

export const PARTICLE_DISTANCE = 'PARTICLE_DISTANCE';
export const PARTICLE_HUE = 'PARTICLE_HUE';
export const PARTICLE_SATURATION = 'PARTICLE_SATURATION';
export const PARTICLE_LIGHTING = 'PARTICLE_LIGHTING';
export const PARTICLE_JITTER_DIST = 'PARTICLE_JITTER_DIST';
export const PARTICLE_BLINK_RATE = 'PARTICLE_BLINK_RATE';
export const PARTICLE_SIZE_MIN = 'PARTICLE_SIZE_MIN';
export const PARTICLE_SIZE_MAX = 'PARTICLE_SIZE_MAX';
